### ISSUE TITLE
Signature Img could be remove easily 

### ISSUE THREAD

**Issue by safemachine-1** [RashadAnsari/pdf-sign#1]
Hello,

Thanks for your idea based on pyHanko.

However, how to be able to encode the signature inside the pdf.
Currently, the signature img is considering like an image and could be remove easily with Preview on Mac for exemple.

**Comment by RashadAnsari** [comment]
Hello @safeRetail, sorry for the late response.

The digital signature is not part of the actual PDF content; it's more like metadata for a PDF. If you want to have the signature image in your PDF, you need to use other tools first to add the signature image where you want, and then add the digital signature in the same place. In that case, you have both the image and the digital signature. Some tools, like Apple Preview, allow users to change the place of the digital signature. In that case, when you move the signature around the PDF, you can still see the actual signature image.

But remember, using the signature image alone does not have any validity, and you still need to add the digital signature. You can still move the signature around in Apple Preview.
